spring:
  jackson:
    serialization-inclusion: non_null
    #Pretty-print JSON responses
    serialization.indent_output: true
  jpa:
    properties.hibernate:
      hbm2ddl.auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://auth-mysql:3306/piggymetrics?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: simon
    password: 123456

server:
  servlet:
    context-path: /uaa
  port: 5000
