security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: 123456
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  jackson:
    serialization-inclusion: non_null
    #Pretty-print JSON responses
    serialization.indent_output: true
  jpa:
    properties.hibernate:
      hbm2ddl.auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://statistics-mysql:3306/piggymetrics?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: simon
    password: 123456

server:
  servlet:
    context-path: /statistics
  port: 7000

rates:
  url: https://api.exchangeratesapi.io